apiVersion: apps/v1
kind: Deployment
metadata:
 name: temperatura-deploy
spec:
 replicas: 2
 selector:
  matchLabels:
   app: temperatura
 template:
  metadata:
   labels:
    app: temperatura
  spec:
   containers:
    - name: temperatura
      image: fabricioveronez/conversao-temperatura
      ports:
       - containerPort: 8080
       
---
apiVersion: v1
kind: Service
metadata:
 name: temperatura-service
spec:
 selector:
  app: temperatura
 ports:
 - protocol: TCP
   port: 8080
   nodePort: 30001
 type: LoadBalancer
