apiVersion: apps/v1
kind: Deployment
metadata:
 name: temperatura-deploy
spec:
 replicas: 2
 selector:
  matchLabels:
   app: temperatura
 template:
  metadata:
   labels:
    app: temperatura
  spec:
   containers:
    - name: temperatura
      image: fabricioveronez/conversao-temperatura
      ports:
       - containerPort: 8080